/**
* Sistema de cadastro com acesso restrito
*
* Usado para fazer controle de clientes de uma academia 
*
* @author Cleber-Soft <cleber-soft@hotmail.com>
*
* @version 1.0
* @package SiS - Academy System
* 
* TELA DE LOGIN
*/
package tela;

import factory.ConnectionFactory;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Cleber Nascimento
 */
public class TelaLogin extends javax.swing.JFrame {
    //Criando Variaveis para Conexao com o Banco
    //PreparedStatement e ResultSet sao Frameworks do pacote java.sql
    // e servem para preparar e executar as instruções SQL
    Connection conexao = null;// Usando a variavel conexao da classe ConnectionFactory
    java.sql.PreparedStatement smt = null;
    ResultSet rs = null;
    
    //CRIANDO METODO LOGAR
    public void logar() {
        //logica principal para pesquisar no banco de dados
        String sql = "select * from login where usuario = ? and senha = ?";
        try {
            //as linhas abaixo preparam a consulta em função do que foi 
            //digitado nas caixas de texto. O '?' é substituído pelo conteúdo
            //das variáveis que são armazenadas em pst.setString
            smt = conexao.prepareStatement(sql);
            smt.setString(1, txtUsuario.getText());
            smt.setString(2, txtSenha.getText());
             //a linha abaixo executa a query(consulta)
             rs = smt.executeQuery();
             //se existir um usuário e senha correspondente
             if(rs.next()){
                 //ABRINDO A TELA PRINCIPAL
                 TelaPrincipal principal = new TelaPrincipal();
                 principal.setVisible(true);
                 this.dispose();
                 //a linha a baixo mostra uma menssagem que deve ser
                 //preenchido todos os campos
                 }else if(txtUsuario.getText().isEmpty()||txtSenha.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null,"Preencha Todos os Campos", 
                        "Login Incorreto", JOptionPane.INFORMATION_MESSAGE);
                         txtSenha.requestFocus();//DEIXA O CURSOR PISCANDO NO CAMPO SENHA
                }else{
                 //MENSAGEM DE ERRO 
                JOptionPane.showMessageDialog(null,"Usuario e/ou Senha Incorreto !!!");
                //LIMPA OS CAMPOS USUARIO E SENHA APOS A MENSAGEM DE ERRO
                //txtUsuario.setText("");
                txtSenha.setText("");
                txtSenha.requestFocus();//DEIXA O CURSOR PISCANDO NO CAMPO SENHA
             }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        txtUsuario.setText("administrador");
        //COLOCANDO IAMGEM NA BARRA DE TAREFA E NA JANELA
        this.setIconImage(new ImageIcon(getClass().getResource("/imagem/login1.png")).getImage());
        
        //VALIDANDO A CONEXAO COM O BANCO
        conexao = ConnectionFactory.getConnection();
        System.out.println(conexao);
        if(conexao != null){
            //MOSTRA A IMAGEM DE CONECTADO
           lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/bancoon.png")));
       }else{
            //MOSTRA A IMAGEM DE DESCONECTADO
           lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/bancooff.png")));
           btnAcessar.setEnabled(false);// DESABILITA O BOTAO ACESSAR
           JOptionPane.showMessageDialog(null,"Desconectado do Banco de Dados!");// MENSAGEM DE DESCONECTADO
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                ImageIcon img = new ImageIcon(new ImageIcon(getClass().getClassLoader().getResource("imagem/login1.png")).getImage());
                g.drawImage(img.getImage(),0,0,d.width,d.height,null);
            }
        };
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        btnAcessar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiS - Academy System v1.0 - Tela Login");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/login3.png"))); // NOI18N
        jLabel2.setToolTipText("USUARIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(172, 221, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(192, 4, 0, 0);
        jPanel1.add(txtUsuario, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/login2.png"))); // NOI18N
        jLabel3.setToolTipText("SENHA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 221, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPanel1.add(txtSenha, gridBagConstraints);

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/bancooff.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(215, 48, 0, 0);
        jPanel1.add(lblStatus, gridBagConstraints);

        btnAcessar.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        btnAcessar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        btnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/acessar-2.gif"))); // NOI18N
        btnAcessar.setText("ACESSAR");
        btnAcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -131;
        gridBagConstraints.ipady = -29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 121, 0, 0);
        jPanel1.add(btnAcessar, gridBagConstraints);

        btnSair.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        btnSair.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.jpg"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = -117;
        gridBagConstraints.ipady = -29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 34, 0, 0);
        jPanel1.add(btnSair, gridBagConstraints);

        jLabel1.setText("VERSÃO BETA 1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(180, 42, 11, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(730, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //EVENTO PARA FECHAR A TELA E LOGIN AO CLICAR NO BOTAO SAIR
        System.exit(0);// FECHA A TELA LOGIN
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        //EVENTO PARA ACESSAR A TELA PRINCIPAL AO CLICAR NO BOTÃO ACESSAR
        logar();//METODO PARA FAZER LOGIN ATRAVES DO BANCO
    }//GEN-LAST:event_btnAcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}