/**
* Sistema de cadastro com acesso restrito
*
* Usado para fazer controle de clientes de uma academia 
*
* @author Cleber-Soft <cleber-soft@hotmail.com>
*
* @version 1.0
* @package SiS - Academy System
* 
* TELA PRINCIPAL
*/
package tela;


import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Cleber Nascimento
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //COLOCANDO IMAGEM NA BARRA DE TAREFA E NA JANELA
        this.setIconImage(new ImageIcon(getClass().getResource("/imagem/login1.png")).getImage());
         //Abre a tela principal Maximizada
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //CENTRALIZA O JFRAMA (TELA PINCIPAL) 
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){
            @Override
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                ImageIcon img = new ImageIcon(new ImageIcon(getClass().getClassLoader().getResource("imagem/academia.png")).getImage());
                g.drawImage(img.getImage(),0,0,d.width,d.height,null);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Cadastro = new javax.swing.JMenu();
        jMenuItem1NovoCadastro = new javax.swing.JMenuItem();
        MenuTelaAlteraLogin = new javax.swing.JMenuItem();
        jMenuItem1Sair = new javax.swing.JMenuItem();
        jMenu2Consulta = new javax.swing.JMenu();
        jMenuItem1ListarCliente = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenu5Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiS - Academy System v1.0");

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setDesktopManager(null);
        jDesktopPane1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1Cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cadastro3.png"))); // NOI18N
        jMenu1Cadastro.setText("Cadastro");
        jMenu1Cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1NovoCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1NovoCadastro.setText("Novo Cadastro");
        jMenuItem1NovoCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1NovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1NovoCadastroActionPerformed(evt);
            }
        });
        jMenu1Cadastro.add(jMenuItem1NovoCadastro);

        MenuTelaAlteraLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenuTelaAlteraLogin.setText("Trocar Senha");
        MenuTelaAlteraLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuTelaAlteraLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTelaAlteraLoginActionPerformed(evt);
            }
        });
        jMenu1Cadastro.add(MenuTelaAlteraLogin);

        jMenuItem1Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1Sair.setText("Sair");
        jMenuItem1Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1SairActionPerformed(evt);
            }
        });
        jMenu1Cadastro.add(jMenuItem1Sair);

        jMenuBar1.add(jMenu1Cadastro);

        jMenu2Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/consulta.png"))); // NOI18N
        jMenu2Consulta.setText("Consulta");
        jMenu2Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1ListarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1ListarCliente.setText("Listar Cliente");
        jMenuItem1ListarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ListarClienteActionPerformed(evt);
            }
        });
        jMenu2Consulta.add(jMenuItem1ListarCliente);

        jMenuBar1.add(jMenu2Consulta);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sobre.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemSobre);

        jMenuBar1.add(jMenuSobre);

        jMenu5Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair2.png"))); // NOI18N
        jMenu5Sair.setText("Sair");
        jMenu5Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1134, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1NovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1NovoCadastroActionPerformed
        //EVENTO PARA ABRIR A TELA CADASTRO (jInternalFrame)
        //CHAMANDO A CLASSE JANELACADASTRO PARA CENTRALIZAR E ABRIR APENAS UMA VEZ
        TelaCadastro dialog = new TelaCadastro(this, rootPaneCheckingEnabled); 
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jDesktopPane1);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1NovoCadastroActionPerformed

    private void jMenuItem1SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1SairActionPerformed
        //EVENTO DO ITEM MENU SAIR PARA SAIR DO PROGRAMA
       //EXIBE UMA CAIXA DE DIALOGO ANTES DE SAIR DO PROGRAMA (MENSSAGEM DE SIM OU NAO)
       int sair = JOptionPane.showConfirmDialog(null,"Tem Certeza que Deseja sair ?","ATENÇÃO !",JOptionPane.YES_NO_OPTION);
       if(sair == JOptionPane.YES_OPTION){//SE SIM FECHA O PROGRAMA  
        System.exit(0);//FECHA O PRORGRAMA
       }
    }//GEN-LAST:event_jMenuItem1SairActionPerformed

    private void jMenuItem1ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ListarClienteActionPerformed
        //EVENTO PARA ABRIR A TELA CONSULTA (jInternalFrame)
        //CHAMANDO A CLASSE JANELACONSULTA PARA CENTRALIZAR E ABRIR APENAS UMA VEZ
        TelaConsulta dialog = new TelaConsulta(this, rootPaneCheckingEnabled); 
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jDesktopPane1);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ListarClienteActionPerformed

    private void jMenu5SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5SairMouseClicked
       //EVENTO DO BOTAO MENU SAIR PARA SAIR DO PROGRAMA
       //EXIBE UMA CAIXA DE DIALOGO ANTES DE SAIR DO PROGRAMA (MENSSAGEM DE SIM OU NAO)
       int sair = JOptionPane.showConfirmDialog(null,"Tem Certeza que Deseja sair ?","ATENÇÃO !",JOptionPane.YES_NO_OPTION);
       if(sair == JOptionPane.YES_OPTION){//SE SIM FECHA O PROGRAMA
        System.exit(0);//FECHA O PRORGRAMA
       }
    }//GEN-LAST:event_jMenu5SairMouseClicked

    private void MenuTelaAlteraLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTelaAlteraLoginActionPerformed
        // TODO add your handling code here:
        TelaAlteraSenha dialog = new TelaAlteraSenha(this, rootPaneCheckingEnabled); 
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jDesktopPane1);
        dialog.setVisible(true);
    }//GEN-LAST:event_MenuTelaAlteraLoginActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
        TelaSobre dialog = new TelaSobre(this, rootPaneCheckingEnabled); 
        dialog.setModal(true);
        dialog.setLocationRelativeTo(jDesktopPane1);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuTelaAlteraLogin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1Cadastro;
    private javax.swing.JMenu jMenu2Consulta;
    private javax.swing.JMenu jMenu5Sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1ListarCliente;
    private javax.swing.JMenuItem jMenuItem1NovoCadastro;
    private javax.swing.JMenuItem jMenuItem1Sair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
